# Generated by Django 4.0.4 on 2022-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidades_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='Imagen'),
        ),
    ]
