# Generated by Django 4.0.4 on 2022-05-31 22:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_alter_departamento_options_alter_departamento_name_and_more'),
        ('persona', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('job', models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Otro')], max_length=50, verbose_name='Trabajo')),
                ('image', models.ImageField(blank=True, upload_to='empleado', verbose_name='Imagen')),
                ('hoja_vida', ckeditor.fields.RichTextField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
                ('habilidades', models.ManyToManyField(to='persona.habilidades')),
            ],
            options={
                'verbose_name': 'Mi Empleado',
                'verbose_name_plural': 'Empleados de la Empresa',
                'ordering': ['-first_name', 'last_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
