# Generated by Django 4.0.4 on 2022-10-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_persona_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='image',
        ),
        migrations.AddField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado', verbose_name='Imagen'),
        ),
    ]
